### ISSUE TITLE
Need to launch the task compile 2 times in order the maven target folder to contains the js file

### ISSUE THREAD

**Issue by blured75** [spaulg/react-jsxtransformer-maven-plugin#2]
To reproduce : 
Add the following build plugin to your pom.xml

<packaging>jar</packaging>

`<build>`
`<plugins>`
    `<plugin>`
        `<groupId>uk.co.codezen</groupId>`
            `<artifactId>react-jsxtransformer-maven-plugin</artifactId>`
             `<version>1.0</version>`
               `<executions>`
                `<execution>`
                 `<goals>`
                  `<goal>compile</goal>`
                   `</goals>`
                    `</execution>`
    `</executions>`
        `<configuration>`
`<sourcePath>D:\git\spring-react-example\src\main\resources\jsx</sourcePath>`
`<targetPath>D:\git\spring-react-example\src\main\resources\static</targetPath>`
`</configuration>`
`</plugin>`
`</plugins>`
`</build>`

Launch mvn clean install
The fact is the file is well copied and transformed during compilation phase however, it is not copied to the mvn target folder and the install does not take it. However If you relaunch the mvn clean install, it works. Seems that there is a dephasing on filesystem or that the file list is made before the compilation phase ?

Regards,
Blured.

**Comment by spaulg** [comment]
Hi,

The maven plugin is really a very simple wrapper around a third party Java Node runtime. The plugin only has one execute method, which runs in whatever phase you specify in the pom file, that extracts the react tools package that is embedded within the jar and runs it with some basic config.

The file list itself is generated by react tools rather than the maven plugin in the chosen execution phase.

I wrote the plugin as a means to save myself from having to install nodejs, as I don't develop with Node and it meant everything could nicely sit within Java using dependencies automatically loaded via Maven.

I believe your issue is because you're target path is within the src/ path and the compile phase runs after the resources phase (thus you don't see the results until the second run of maven). You need to move this to target and ensure you don't overwrite the generated output (such as by the resources plugin) by ignoring those files in src, or, setting both the source and target paths to the target/ directory and transforming what has already been copied over by other plugins.

Hope this helps.

Thanks,
Simon
